"""make_email_optional_in_alunos

Revision ID: 0363b596667a
Revises: 8ab3bf85f2d1
Create Date: 2025-11-12 18:47:56.479520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0363b596667a'
down_revision = '8ab3bf85f2d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    op.alter_column('alunos', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
