"""Adicionar tabela data_prova entre turma e prova

Revision ID: 0a60f4c0a6fd
Revises: f1234567890e
Create Date: 2025-12-01 23:54:19.442772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a60f4c0a6fd'
down_revision = 'f1234567890e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_prova',
    sa.Column('turma_id', sa.Uuid(), nullable=False),
    sa.Column('prova_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_prova')
    # ### end Alembic commands ###