"""add_questao_and_questao_opcao_tables

Revision ID: 4bc74ec62569
Revises: 0363b596667a
Create Date: 2025-11-15 16:37:43.222442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc74ec62569'
down_revision = '0363b596667a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questoes',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prova_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_opcoes',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questao_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('aluno_turma')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno_turma',
    sa.Column('turma_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aluno_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('aluno_turma_aluno_id_fkey')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('aluno_turma_turma_id_fkey')),
    sa.PrimaryKeyConstraint('turma_id', 'aluno_id', name=op.f('aluno_turma_pkey'))
    )
    op.drop_table('questao_opcoes')
    op.drop_table('questoes')
    # ### end Alembic commands ###