"""initial schema
import sqlmodel

Revision ID: 4ede1697b4d3
Revises: 
Create Date: 2025-11-28 23:36:27.213666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4ede1697b4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acessos',
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=False)
    op.create_index(op.f('ix_alunos_matricula'), 'alunos', ['matricula'], unique=True)
    op.create_table('turmas',
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('provas',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provas_name'), 'provas', ['name'], unique=False)
    op.create_table('turma_aluno',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'aluno_id')
    )
    op.create_table('correcoes',
    sa.Column('aluno_id', sa.Uuid(), nullable=False),
    sa.Column('turma_id', sa.Uuid(), nullable=False),
    sa.Column('prova_id', sa.Uuid(), nullable=False),
    sa.Column('corrigido_por', sa.Uuid(), nullable=False),
    sa.Column('data_correcao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('total_questoes', sa.Integer(), nullable=True),
    sa.Column('acertos', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['corrigido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prova_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma_provas',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=True),
    sa.Column('prova_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_randomizacoes',
    sa.Column('questoes_order', sa.JSON(), nullable=True),
    sa.Column('alternativas_order', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('turma_prova_id', sa.UUID(), nullable=True),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_prova_id'], ['turma_provas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correcao_respostas',
    sa.Column('correcao_id', sa.Uuid(), nullable=False),
    sa.Column('questao_numero', sa.Integer(), nullable=False),
    sa.Column('resposta_marcada', sa.String(length=10), nullable=True),
    sa.Column('resposta_correta', sa.String(length=10), nullable=True),
    sa.Column('esta_correta', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['correcao_id'], ['correcoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questao_opcoes',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questao_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao_opcoes')
    op.drop_table('correcao_respostas')
    op.drop_table('aluno_randomizacoes')
    op.drop_table('turma_provas')
    op.drop_table('questoes')
    op.drop_table('correcoes')
    op.drop_table('turma_aluno')
    op.drop_index(op.f('ix_provas_name'), table_name='provas')
    op.drop_table('provas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_alunos_matricula'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_table('acessos')
    # ### end Alembic commands ###