"""add_deleted_column_to_provas

Revision ID: 8aa2c615cdc9
Revises: 0a60f4c0a6fd
Create Date: 2025-12-02 22:45:12.390717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa2c615cdc9'
down_revision = '0a60f4c0a6fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('provas', sa.Column('deleted', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE provas SET deleted = FALSE WHERE deleted IS NULL')
    # Make column NOT NULL
    op.alter_column('provas', 'deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provas', 'deleted')
    # ### end Alembic commands ###