"""add_turma_and_aluno_tables_with_many_to_many

Revision ID: 8ab3bf85f2d1
Revises: adba7c6988ee
Create Date: 2025-11-12 08:42:24.561423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab3bf85f2d1'
down_revision = 'adba7c6988ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), server_default='gen_random_uuid()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    op.create_index(op.f('ix_alunos_matricula'), 'alunos', ['matricula'], unique=True)
    op.create_table('turmas',
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('materia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default='gen_random_uuid()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma_aluno',
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'aluno_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_aluno')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_alunos_matricula'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###