"""add_created_by_column_to_provas

Revision ID: adba7c6988ee
Revises: 
Create Date: 2025-11-05 14:55:43.914600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adba7c6988ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_provas_name'), 'provas', ['name'], unique=False)
    op.create_foreign_key(None, 'provas', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provas', type_='foreignkey')
    op.drop_index(op.f('ix_provas_name'), table_name='provas')
    op.drop_column('provas', 'created_by')
    # ### end Alembic commands ###